name: Python package

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        run: |
          pip install pipenv
      - name: Install dependencies
        run: |
          pipenv install --dev --deploy
      - name: Test with pytest
        run: |
          pipenv run pytest
      - name: Login to CoreFiling docker
        uses: docker/login-action@v1
        with:
          registry: docker.corefiling.com
          username: ${{ secrets.CFL_DOCKER_USERNAME }}
          password: ${{ secrets.CFL_DOCKER_PASSWORD }}
      - name: Prepare docker image
        run: |
          pipenv lock --keep-outdated --requirements > requirements.txt
          cat requirements.txt
      - name: Build docker image
        run: |
          docker build . -t docker.corefiling.com/helloworld:$GITHUB_RUN_NUMBER -t docker.corefiling.com/helloworld:latest
