name: Python package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python.version }}
      - name: Debug 1
        run: |
          which python
          which pip
          which pipenv || true
      - name: Install pipenv
        run: |
          sudo pip install pipenv
      - name: Debug 2
        run: |
          which python
          which pip
          which pipenv || true
      - name: Install dependencies
        run: |
          pipenv install --dev --deploy
      - name: Test with pytest
        run: |
          python -m pipenv run pytest